IOC_TOP = {{ template_path.parent.parent }}
IOC_INSTANCE_PATH := $(shell pwd)

# Set PRODUCTION_IOC to 1 to move from a testing to a production IOC:
PRODUCTION_IOC := 0

PROJECT_NAME := {{ project_name }}
PROJECT_PATH := {{ tsproj_path }}
PLC := {{ plc_name }}

PYTMC_OPTS := 
PREFIX := PLC:$(PLC)

# With two $$, as in $$(IOCNAME) below, this will be expanded in the
# environment of st.cmd:
DB_PARAMETERS := 'PREFIX=$(PREFIX):,IOCNAME=$$(IOC),IOC=$$(IOC)'

include $(IOC_TOP)/iocBoot/templates/Makefile.base
