IOC_TOP = {{ template_path.parent.parent }}
IOC_INSTANCE_PATH := $(shell pwd)

PROJECT_NAME = {{ project_name }}
PROJECT_PATH := {{ tsproj_path }}
PLC = {{ plc_name }}

PYTMC_OPTS = 
PREFIX = PREFIX:

include $(IOC_TOP)/iocBoot/templates/Makefile.base
